/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ToolCategory = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const ToolPage = IDL.Record({
  'id' : IDL.Nat,
  'files' : IDL.Vec(ExternalBlob),
  'title' : IDL.Text,
  'content' : IDL.Text,
  'category' : ToolCategory,
});
export const Tool = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'usageCount' : IDL.Nat,
  'slug' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'iconName' : IDL.Text,
  'category' : IDL.Text,
  'iconUrl' : IDL.Text,
  'route' : IDL.Text,
  'favoriteCount' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'displayName' : IDL.Opt(IDL.Text),
  'userId' : IDL.Principal,
  'email' : IDL.Opt(IDL.Text),
  'totalCreditsAllowed' : IDL.Nat,
  'creditsConsumed' : IDL.Nat,
  'registrationDate' : IDL.Int,
});
export const UserCreditStatus = IDL.Record({
  'displayName' : IDL.Text,
  'userId' : IDL.Principal,
  'creditsRemaining' : IDL.Nat,
  'totalCreditsAllowed' : IDL.Nat,
  'creditsConsumed' : IDL.Nat,
});
export const UserFavorites = IDL.Record({
  'userId' : IDL.Principal,
  'favoriteToolIds' : IDL.Vec(IDL.Text),
});
export const UserPreferences = IDL.Record({
  'theme' : IDL.Text,
  'userId' : IDL.Principal,
  'notificationSettings' : IDL.Opt(IDL.Text),
  'defaultMeasurementUnit' : IDL.Opt(IDL.Text),
});
export const SearchHistory = IDL.Record({
  'userId' : IDL.Principal,
  'timestamp' : IDL.Int,
  'resultsCount' : IDL.Nat,
  'searchQuery' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addSearchHistory' : IDL.Func([IDL.Principal, IDL.Text, IDL.Nat], [], []),
  'addToolCategory' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'addToolPage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Vec(ExternalBlob)],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'consumeCredits' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'editDisplayName' : IDL.Func([IDL.Opt(IDL.Text)], [], []),
  'getAllToolCategories' : IDL.Func([], [IDL.Vec(ToolCategory)], ['query']),
  'getAllToolPages' : IDL.Func([], [IDL.Vec(ToolPage)], ['query']),
  'getAllToolUsageCounts' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getAllTools' : IDL.Func([], [IDL.Vec(Tool)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCreditBalance' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserCreditStatus)],
      ['query'],
    ),
  'getCurrentUserFavorites' : IDL.Func([], [IDL.Opt(UserFavorites)], ['query']),
  'getCurrentUserPreferences' : IDL.Func(
      [],
      [IDL.Opt(UserPreferences)],
      ['query'],
    ),
  'getSearchHistory' : IDL.Func([], [IDL.Vec(SearchHistory)], ['query']),
  'getToolCategory' : IDL.Func([IDL.Nat], [IDL.Opt(ToolCategory)], ['query']),
  'getToolPage' : IDL.Func([IDL.Nat], [IDL.Opt(ToolPage)], ['query']),
  'getToolPagesByCategory' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ToolPage)],
      ['query'],
    ),
  'getToolUsageCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getUserDisplayName' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(IDL.Text)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeTools' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllCreditBalances' : IDL.Func([], [IDL.Vec(UserCreditStatus)], []),
  'recordToolUsage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveCurrentUserFavorites' : IDL.Func([UserFavorites], [], []),
  'saveCurrentUserPreferences' : IDL.Func([UserPreferences], [], []),
  'updateProfileCredits' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ToolCategory = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const ToolPage = IDL.Record({
    'id' : IDL.Nat,
    'files' : IDL.Vec(ExternalBlob),
    'title' : IDL.Text,
    'content' : IDL.Text,
    'category' : ToolCategory,
  });
  const Tool = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'usageCount' : IDL.Nat,
    'slug' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'iconName' : IDL.Text,
    'category' : IDL.Text,
    'iconUrl' : IDL.Text,
    'route' : IDL.Text,
    'favoriteCount' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'displayName' : IDL.Opt(IDL.Text),
    'userId' : IDL.Principal,
    'email' : IDL.Opt(IDL.Text),
    'totalCreditsAllowed' : IDL.Nat,
    'creditsConsumed' : IDL.Nat,
    'registrationDate' : IDL.Int,
  });
  const UserCreditStatus = IDL.Record({
    'displayName' : IDL.Text,
    'userId' : IDL.Principal,
    'creditsRemaining' : IDL.Nat,
    'totalCreditsAllowed' : IDL.Nat,
    'creditsConsumed' : IDL.Nat,
  });
  const UserFavorites = IDL.Record({
    'userId' : IDL.Principal,
    'favoriteToolIds' : IDL.Vec(IDL.Text),
  });
  const UserPreferences = IDL.Record({
    'theme' : IDL.Text,
    'userId' : IDL.Principal,
    'notificationSettings' : IDL.Opt(IDL.Text),
    'defaultMeasurementUnit' : IDL.Opt(IDL.Text),
  });
  const SearchHistory = IDL.Record({
    'userId' : IDL.Principal,
    'timestamp' : IDL.Int,
    'resultsCount' : IDL.Nat,
    'searchQuery' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addSearchHistory' : IDL.Func([IDL.Principal, IDL.Text, IDL.Nat], [], []),
    'addToolCategory' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'addToolPage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Vec(ExternalBlob)],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'consumeCredits' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'editDisplayName' : IDL.Func([IDL.Opt(IDL.Text)], [], []),
    'getAllToolCategories' : IDL.Func([], [IDL.Vec(ToolCategory)], ['query']),
    'getAllToolPages' : IDL.Func([], [IDL.Vec(ToolPage)], ['query']),
    'getAllToolUsageCounts' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getAllTools' : IDL.Func([], [IDL.Vec(Tool)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCreditBalance' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserCreditStatus)],
        ['query'],
      ),
    'getCurrentUserFavorites' : IDL.Func(
        [],
        [IDL.Opt(UserFavorites)],
        ['query'],
      ),
    'getCurrentUserPreferences' : IDL.Func(
        [],
        [IDL.Opt(UserPreferences)],
        ['query'],
      ),
    'getSearchHistory' : IDL.Func([], [IDL.Vec(SearchHistory)], ['query']),
    'getToolCategory' : IDL.Func([IDL.Nat], [IDL.Opt(ToolCategory)], ['query']),
    'getToolPage' : IDL.Func([IDL.Nat], [IDL.Opt(ToolPage)], ['query']),
    'getToolPagesByCategory' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ToolPage)],
        ['query'],
      ),
    'getToolUsageCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getUserDisplayName' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeTools' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllCreditBalances' : IDL.Func([], [IDL.Vec(UserCreditStatus)], []),
    'recordToolUsage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveCurrentUserFavorites' : IDL.Func([UserFavorites], [], []),
    'saveCurrentUserPreferences' : IDL.Func([UserPreferences], [], []),
    'updateProfileCredits' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };