/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface SearchHistory {
  'userId' : Principal,
  'timestamp' : bigint,
  'resultsCount' : bigint,
  'searchQuery' : string,
}
export interface Tool {
  'id' : bigint,
  'name' : string,
  'usageCount' : bigint,
  'slug' : string,
  'tags' : Array<string>,
  'description' : string,
  'iconName' : string,
  'category' : string,
  'iconUrl' : string,
  'route' : string,
  'favoriteCount' : bigint,
}
export interface ToolCategory {
  'id' : bigint,
  'name' : string,
  'description' : string,
}
export interface ToolPage {
  'id' : bigint,
  'files' : Array<ExternalBlob>,
  'title' : string,
  'content' : string,
  'category' : ToolCategory,
}
export interface UserCreditStatus {
  'displayName' : string,
  'userId' : Principal,
  'creditsRemaining' : bigint,
  'totalCreditsAllowed' : bigint,
  'creditsConsumed' : bigint,
}
export interface UserFavorites {
  'userId' : Principal,
  'favoriteToolIds' : Array<string>,
}
export interface UserPreferences {
  'theme' : string,
  'userId' : Principal,
  'notificationSettings' : [] | [string],
  'defaultMeasurementUnit' : [] | [string],
}
export interface UserProfile {
  'displayName' : [] | [string],
  'userId' : Principal,
  'email' : [] | [string],
  'totalCreditsAllowed' : bigint,
  'creditsConsumed' : bigint,
  'registrationDate' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addSearchHistory' : ActorMethod<[Principal, string, bigint], undefined>,
  'addToolCategory' : ActorMethod<[string, string], bigint>,
  'addToolPage' : ActorMethod<
    [string, string, bigint, Array<ExternalBlob>],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'consumeCredits' : ActorMethod<[bigint], boolean>,
  'editDisplayName' : ActorMethod<[[] | [string]], undefined>,
  'getAllToolCategories' : ActorMethod<[], Array<ToolCategory>>,
  'getAllToolPages' : ActorMethod<[], Array<ToolPage>>,
  'getAllToolUsageCounts' : ActorMethod<[], Array<[string, bigint]>>,
  'getAllTools' : ActorMethod<[], Array<Tool>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCreditBalance' : ActorMethod<[Principal], [] | [UserCreditStatus]>,
  'getCurrentUserFavorites' : ActorMethod<[], [] | [UserFavorites]>,
  'getCurrentUserPreferences' : ActorMethod<[], [] | [UserPreferences]>,
  'getSearchHistory' : ActorMethod<[], Array<SearchHistory>>,
  'getToolCategory' : ActorMethod<[bigint], [] | [ToolCategory]>,
  'getToolPage' : ActorMethod<[bigint], [] | [ToolPage]>,
  'getToolPagesByCategory' : ActorMethod<[bigint], Array<ToolPage>>,
  'getToolUsageCount' : ActorMethod<[string], bigint>,
  'getUserDisplayName' : ActorMethod<[Principal], [] | [string]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeTools' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllCreditBalances' : ActorMethod<[], Array<UserCreditStatus>>,
  'recordToolUsage' : ActorMethod<[Principal, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveCurrentUserFavorites' : ActorMethod<[UserFavorites], undefined>,
  'saveCurrentUserPreferences' : ActorMethod<[UserPreferences], undefined>,
  'updateProfileCredits' : ActorMethod<[Principal, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];